name: Build
on:
  pull_request:
    branches: [main]
    types: [opened, reopened, updated, synchronize]

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    container: projectserum/build:v0.24.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Install Node dependencies
        run: yarn install
      - name: Create a new Solana keypair
        run: solana-keygen new -s --no-bip39-passphrase
      - name: Run tests
        run: |
          yarn test:validator &
          sleep 30
          yarn test
